### ISSUE TITLE
Broken demo pages

### ISSUE THREAD

**Issue by lulalachen** [LeetCodeTaiwan/animix#10]
Demo page seems broken

**Comment by YoEugene** [comment]
// 酷耶我第一次用 issue !!

**Comment by lulalachen** [comment]
晚點來修修看 我也不知道為啥 感覺只能重新build然後推上來看看

**Comment by yehjames** [comment]
Demo page seems broken --> 可以快點修嗎~~十萬火急  我下午要在GG分享這個 QQQQQ

**Comment by yehjames** [comment]
這要怎麼玩以前的版本呀 我在GG 不能用github的指令去取回以前的版本

**Comment by yehjames** [comment]
@lulalachen @YoEugene  麻煩兩位大神了~~

**Comment by yehjames** [comment]
拜託在三點以前先修好~~~

**Comment by lulalachen** [comment]
哪泥!! 好喔 我來修

**Comment by yehjames** [comment]
感恩感恩~

**Comment by lulalachen** [comment]
Fixed in commit[1813982](https://github.com/LeetCodeTaiwan/animix/commit/181398258ceb458941e0f36bc9e30708f4bb2d04)

**Comment by lulalachen** [comment]
I do nothing but rebuild and redeploy

**Comment by yehjames** [comment]
謝囉~ 下午先別動囉

**Comment by YoEugene** [comment]
@lulalachen GJ!
